name: Mint Identity Token
on:
  workflow_call:
    outputs:
      token:
        description: "The minted identity token"
        value: ${{ jobs.mint_token.outputs.token }}

jobs:
  mint_token:
    runs-on: ubuntu-latest
    outputs:
      token: ${{ steps.mint_identity_token.outputs.token }}
    steps:
      - name: 'Mint identity token'
        id: 'mint_identity_token'
        if: |-
          ${{ vars.APP_ID }}
        uses: 'actions/create-github-app-token@v2'
        with:
          app-id: '${{ vars.APP_ID }}'
          private-key: '${{ secrets.APP_PRIVATE_KEY }}'
          permission-contents: 'read'
          permission-issues: 'write'
          permission-pull-requests: 'write'
